import React from 'react';
import FontCard from './FontCard';

const FontSelector = ({ selectedFont, onFontSelect }) => {
  const fonts = [
    {
      id: 'handwriting1',
      name: 'Academic Script',
      description: 'Clean, professional handwriting suitable for exams and official assignments.',
      style: 'neat',
      previewText: 'The quick brown fox jumps over the lazy dog. 1234567890'
    },
    {
      id: 'handwriting2',
      name: 'Casual Notes',
      description: 'Natural, everyday handwriting with a relaxed feel for homework and notes.',
      style: 'casual',
      previewText: 'Mathematics assignment on quadratic equations and derivatives.'
    },
    {
      id: 'handwriting3',
      name: 'Creative Flow',
      description: 'Artistic handwriting with personality, perfect for creative projects.',
      style: 'artistic',
      previewText: 'English literature analysis of Shakespearean sonnets and themes.'
    },
    {
      id: 'handwriting4',
      name: 'Quick Notes',
      description: 'Fast, slightly messy handwriting that looks like real classroom notes.',
      style: 'messy',
      previewText: 'Physics problems on thermodynamics and quantum mechanics.'
    },
    {
      id: 'handwriting5',
      name: 'Formal Script',
      description: 'Elegant, traditional handwriting for official documents and submissions.',
      style: 'formal',
      previewText: 'History essay on the impact of industrial revolution.'
    },
    {
      id: 'handwriting6',
      name: 'Student Print',
      description: 'Clear, printed handwriting ideal for science and math assignments.',
      style: 'neat',
      previewText: 'Chemical equations and biological diagrams with labels.'
    },
  ];

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-lg font-semibold text-gray-800 mb-2">Select Handwriting Style</h3>
        <p className="text-gray-600">
          Choose a handwriting style that matches your assignment type. Each style is generated by AI to look natural.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {fonts.map((font) => (
          <FontCard
            key={font.id}
            fontId={font.id}
            name={font.name}
            description={font.description}
            style={font.style}
            previewText={font.previewText}
            isSelected={selectedFont === font.id}
            onSelect={onFontSelect}
          />
        ))}
      </div>

      <div className="bg-gradient-to-r from-primary-50 to-blue-50 p-6 rounded-xl border border-primary-100">
        <div className="flex items-start space-x-4">
          <div className="w-10 h-10 bg-primary-100 rounded-lg flex items-center justify-center flex-shrink-0">
            <svg className="w-5 h-5 text-primary-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </div>
          <div>
            <h4 className="font-medium text-gray-800 mb-1">Pro Tip</h4>
            <p className="text-sm text-gray-600">
              The AI will generate unique variations of the selected handwriting style for each assignment, 
              making it look like it was actually written by hand.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default FontSelector;