import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAssignment } from '../context/AssignmentContext';

const DownloadAssignment = () => {
  const { assignment } = useAssignment();
  const navigate = useNavigate();
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadFormat, setDownloadFormat] = useState('');

  // Get font display name
  const getFontDisplayName = (fontId) => {
    const fontNames = {
      handwriting1: 'Academic Script',
      handwriting2: 'Casual Notes', 
      handwriting3: 'Creative Flow',
      handwriting4: 'Quick Notes',
      handwriting5: 'Formal Script',
      handwriting6: 'Student Print',
    };
    return fontNames[fontId] || fontId;
  };

  // Get font class
  const getFontClass = () => {
    const fontMap = {
      handwriting1: 'font-handwriting1 handwriting-academic',
      handwriting2: 'font-handwriting2 handwriting-casual',
      handwriting3: 'font-handwriting3 handwriting-artistic',
      handwriting4: 'font-handwriting4 handwriting-notes',
      handwriting5: 'font-handwriting5 handwriting-formal',
      handwriting6: 'font-handwriting6 handwriting-print',
    };
    return fontMap[assignment.selectedFont] || 'font-handwriting1 handwriting-academic';
  };

  // Text file download (with lined paper effect in text)
  const handleTextDownload = () => {
    setDownloadFormat('text');
    setIsDownloading(true);
    
    const textContent = `
============================================
                ASSIGNMENT
============================================

Title: ${assignment.title || 'Untitled Assignment'}
Subject: ${assignment.subject || 'Not specified'}
Topic: ${assignment.topic || 'General'}
Grade Level: ${assignment.gradeLevel || 'High School'}
Difficulty: ${assignment.difficulty || 'Medium'}
Due Date: ${assignment.dueDate ? new Date(assignment.dueDate).toLocaleDateString() : 'Not set'}
Handwriting Style: ${getFontDisplayName(assignment.selectedFont)} (${assignment.selectedFont})

============================================
                 QUESTIONS
============================================

${assignment.questions.map((q, i) => {
  let questionText = `${i + 1}. ${q.text}`;
  if (q.marks) questionText += ` [${q.marks} marks]`;
  if (assignment.includeAnswers && q.answer) questionText += `\n   Answer: ${q.answer}`;
  
  // Add lined paper effect
  questionText += '\n' + '_'.repeat(80) + '\n';
  
  return questionText;
}).join('\n')}

============================================
Total Questions: ${assignment.questions.length}
Total Marks: ${assignment.questions.reduce((sum, q) => sum + (q.marks || 0), 0)}
Handwriting Style: ${getFontDisplayName(assignment.selectedFont)}
Generated on: ${new Date().toLocaleDateString()}
Generated by: HandwrittenAI
============================================
    `;
    
    const blob = new Blob([textContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${assignment.title || 'assignment'}_${assignment.selectedFont || 'handwriting1'}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    setTimeout(() => {
      setIsDownloading(false);
      setDownloadFormat('');
    }, 500);
  };

  // Create HTML with EXACT same styling as AssignmentPreview
  const createHTMLForPDF = () => {
    const fontClass = getFontClass();
    
    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>${assignment.title || 'Assignment'}</title>
        <link href="https://fonts.googleapis.com/css2?family=Caveat:wght@400..700&family=Kalam:wght@300;400;700&family=Homemade+Apple&family=Patrick+Hand&family=Dancing+Script:wght@400..700&family=Shadows+Into+Light&display=swap" rel="stylesheet">
        <style>
          @page { margin: 0; }
          body { 
            margin: 0;
            padding: 40px;
            background: white;
            font-family: Arial, sans-serif;
            line-height: 1.6;
          }
          
          /* EXACT SAME FONT CLASSES AS PREVIEW */
          .font-handwriting1 { 
            font-family: 'Caveat', cursive;
            font-size: 22px;
            letter-spacing: 0.5px;
            line-height: 1.8;
          }
          .font-handwriting2 { 
            font-family: 'Kalam', cursive;
            font-size: 20px;
            letter-spacing: -0.3px;
            line-height: 1.6;
            font-weight: 300;
          }
          .font-handwriting3 { 
            font-family: 'Homemade Apple', cursive;
            font-size: 22px;
            letter-spacing: 1px;
            line-height: 2;
          }
          .font-handwriting4 { 
            font-family: 'Patrick Hand', cursive;
            font-size: 20px;
            letter-spacing: 0.8px;
            line-height: 1.5;
          }
          .font-handwriting5 { 
            font-family: 'Dancing Script', cursive;
            font-size: 22px;
            letter-spacing: 1.2px;
            line-height: 2.2;
          }
          .font-handwriting6 { 
            font-family: 'Shadows Into Light', cursive;
            font-size: 20px;
            letter-spacing: 0.2px;
            line-height: 1.4;
          }
          
          /* LINED PAPER EFFECT - EXACT LIKE PREVIEW */
          .lined-paper {
            background-image: linear-gradient(to bottom, transparent 94%, rgba(0,0,0,0.08) 95%);
            background-size: 100% 2em;
            line-height: 2em;
            padding: 2em 0;
          }
          
          /* NOTEBOOK MARGIN - EXACT LIKE PREVIEW */
          .notebook-margin {
            border-left: 3px solid #ef4444;
            padding-left: 2.5em;
            margin-left: 1em;
            position: relative;
          }
          .notebook-margin::before {
            content: '';
            position: absolute;
            left: -1em;
            top: 0;
            bottom: 0;
            width: 2px;
            background: #ef4444;
            opacity: 0.3;
          }
          
          /* PAPER TEXTURE - EXACT LIKE PREVIEW */
          .paper-texture {
            background-image: 
              radial-gradient(#00000008 1px, transparent 1px),
              radial-gradient(#00000003 1px, transparent 1px);
            background-size: 20px 20px;
            background-position: 0 0, 10px 10px;
          }
          
          /* INK BLEED EFFECT - EXACT LIKE PREVIEW */
          .ink-bleed {
            text-shadow: 
              0.3px 0.3px 0px rgba(0,0,0,0.15),
              0.2px 0px 0px rgba(0,0,0,0.1),
              0px 0.2px 0px rgba(0,0,0,0.1);
          }
          
          /* Assignment container */
          .assignment-container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
          }
          
          /* Header */
          .assignment-header {
            text-align: center;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 2px solid #e5e7eb;
          }
          
          .assignment-title {
            font-size: 36px;
            font-weight: bold;
            margin-bottom: 10px;
          }
          
          .title-line {
            height: 3px;
            width: 100px;
            background: linear-gradient(to right, #3b82f6, #1d4ed8);
            margin: 10px auto;
            border-radius: 2px;
          }
          
          /* Details grid */
          .details-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 20px;
            margin: 30px 0;
          }
          
          .detail-item {
            display: flex;
            align-items: center;
            gap: 10px;
          }
          
          .icon {
            width: 20px;
            height: 20px;
            flex-shrink: 0;
          }
          
          /* Questions */
          .question-container {
            margin: 30px 0;
            padding: 20px;
            background: white;
            border: 2px solid #d1d5db;
            border-radius: 12px;
          }
          
          .question-header {
            display: flex;
            align-items: center;
            gap: 15px;
            margin-bottom: 20px;
          }
          
          .question-number {
            width: 40px;
            height: 40px;
            background: #dbeafe;
            color: #1d4ed8;
            border-radius: 10px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
            font-size: 18px;
          }
          
          .question-text {
            margin: 15px 0;
          }
          
          /* Options for MCQs */
          .options-grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 10px;
            margin: 15px 0;
          }
          
          .option-item {
            display: flex;
            align-items: center;
            gap: 12px;
            padding: 12px;
            background: #f9fafb;
            border-radius: 8px;
          }
          
          .option-letter {
            width: 30px;
            height: 30px;
            background: white;
            border: 2px solid #9ca3af;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
          }
          
          /* Answer section */
          .answer-section {
            background: #f0fdf4;
            border-left: 4px solid #10b981;
            padding: 15px;
            margin-top: 15px;
            border-radius: 6px;
          }
          
          .answer-label {
            font-weight: bold;
            color: #065f46;
            margin-bottom: 5px;
          }
          
          /* Footer */
          .assignment-footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
            text-align: center;
            color: #6b7280;
            font-size: 14px;
          }
          
          .watermark {
            opacity: 0.5;
            font-style: italic;
          }
        </style>
      </head>
      <body>
        <div class="assignment-container">
          <!-- Lined Paper Background -->
          <div class="lined-paper paper-texture">
            <div class="notebook-margin">
              
              <!-- Header -->
              <div class="assignment-header">
                <h1 class="assignment-title ${fontClass} ink-bleed">
                  ${assignment.title || 'Assignment Title'}
                </h1>
                <div class="title-line"></div>
                <p class="${fontClass}" style="color: #6b7280; margin-top: 10px;">
                  ${assignment.subject || ''} • ${assignment.topic || ''}
                </p>
              </div>
              
              <!-- Details -->
              <div class="details-grid">
                <div class="detail-item">
                  <svg class="icon" viewBox="0 0 24 24" fill="#3b82f6">
                    <path d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" stroke="currentColor" stroke-width="2" fill="none"/>
                  </svg>
                  <span class="${fontClass}">
                    <strong>Due Date:</strong> ${assignment.dueDate ? new Date(assignment.dueDate).toLocaleDateString() : 'Not set'}
                  </span>
                </div>
                
                <div class="detail-item">
                  <svg class="icon" viewBox="0 0 24 24" fill="#3b82f6">
                    <path d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" stroke="currentColor" stroke-width="2" fill="none"/>
                  </svg>
                  <span class="${fontClass}">
                    <strong>Total Marks:</strong> ${assignment.questions.reduce((sum, q) => sum + (q.marks || 0), 0)} marks
                  </span>
                </div>
                
                <div class="detail-item">
                  <svg class="icon" viewBox="0 0 24 24" fill="#3b82f6">
                    <path d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" stroke="currentColor" stroke-width="2" fill="none"/>
                  </svg>
                  <span class="${fontClass}">
                    <strong>Student:</strong> [Student Name]
                  </span>
                </div>
                
                <div class="detail-item">
                  <svg class="icon" viewBox="0 0 24 24" fill="#3b82f6">
                    <path d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" stroke="currentColor" stroke-width="2" fill="none"/>
                  </svg>
                  <span class="${fontClass}">
                    <strong>Includes Answers:</strong> ${assignment.includeAnswers ? 'Yes' : 'No'}
                  </span>
                </div>
              </div>
              
              <!-- Instructions -->
              ${assignment.instructions ? `
                <div style="background: #fef3c7; padding: 15px; border-left: 4px solid #f59e0b; border-radius: 6px; margin: 25px 0;">
                  <div style="display: flex; align-items: center; gap: 10px; margin-bottom: 8px;">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="#f59e0b">
                      <path d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-2.5L13.732 4c-.77-.833-1.998-.833-2.732 0L4.342 16.5c-.77.833.192 2.5 1.732 2.5z" stroke="currentColor" stroke-width="2" fill="none"/>
                    </svg>
                    <strong style="color: #92400e;">Instructions</strong>
                  </div>
                  <div class="${fontClass}" style="color: #92400e;">
                    ${assignment.instructions}
                  </div>
                </div>
              ` : ''}
              
              <!-- Questions -->
              <h2 style="color: #1e40af; border-bottom: 2px solid #dbeafe; padding-bottom: 10px; margin: 30px 0 20px;">
                Questions
              </h2>
              
              ${assignment.questions.map((q, i) => `
                <div class="question-container">
                  <div class="question-header">
                    <div class="question-number">${i + 1}</div>
                    <div>
                      <h3 class="${fontClass}" style="margin: 0; font-weight: bold;">Question ${i + 1}</h3>
                      <div style="display: flex; gap: 8px; margin-top: 5px;">
                        <span style="background: #e5e7eb; color: #374151; padding: 4px 8px; border-radius: 4px; font-size: 12px;">
                          ${q.type || 'short'}
                        </span>
                        ${q.marks ? `
                          <span style="background: #dbeafe; color: #1e40af; padding: 4px 8px; border-radius: 4px; font-size: 12px;">
                            ${q.marks} marks
                          </span>
                        ` : ''}
                      </div>
                    </div>
                  </div>
                  
                  <div class="question-text ${fontClass} ink-bleed">
                    ${q.text || 'No question text provided'}
                  </div>
                  
                  ${q.type === 'multiple' && q.options ? `
                    <div style="margin-top: 20px;">
                      <p style="font-weight: bold; color: #374151; margin-bottom: 10px;">Options:</p>
                      <div class="options-grid">
                        ${Object.entries(q.options).map(([key, value]) => `
                          <div class="option-item">
                            <div class="option-letter">${key.toUpperCase()}</div>
                            <span class="${fontClass}">${value}</span>
                            ${q.correctOption === key ? `
                              <span style="margin-left: auto; background: #10b981; color: white; padding: 2px 8px; border-radius: 12px; font-size: 11px;">
                                Correct
                              </span>
                            ` : ''}
                          </div>
                        `).join('')}
                      </div>
                    </div>
                  ` : ''}
                  
                  ${assignment.includeAnswers && q.answer ? `
                    <div class="answer-section">
                      <div class="answer-label">Expected Answer:</div>
                      <div class="${fontClass} ink-bleed" style="color: #065f46;">
                        ${q.answer}
                      </div>
                    </div>
                  ` : ''}
                </div>
              `).join('')}
              
              <!-- Footer -->
              <div class="assignment-footer">
                <div class="${fontClass}" style="margin-bottom: 10px;">
                  <strong>Handwriting Style:</strong> ${getFontDisplayName(assignment.selectedFont)} (${assignment.selectedFont})
                </div>
                <div style="display: flex; justify-content: space-between; color: #6b7280; font-size: 13px;">
                  <div>Page 1</div>
                  <div>Generated by HandwrittenAI</div>
                  <div>Total Marks: ${assignment.questions.reduce((sum, q) => sum + (q.marks || 0), 0)}</div>
                </div>
                <div class="watermark ${fontClass}" style="margin-top: 15px;">
                  This assignment was generated with ${getFontDisplayName(assignment.selectedFont)} handwriting style
                </div>
              </div>
              
            </div>
          </div>
        </div>
      </body>
      </html>
    `;
  };

 const handlePDFDownload = async () => {
  setDownloadFormat('pdf');
  setIsDownloading(true);

  try {
    const html2canvas = (await import('html2canvas')).default;
    const { jsPDF } = await import('jspdf');

    const htmlContent = createHTMLForPDF();

    const iframe = document.createElement('iframe');
    iframe.style.position = 'absolute';
    iframe.style.width = '794px';
    iframe.style.top = '-9999px';
    document.body.appendChild(iframe);

    const iframeDoc = iframe.contentDocument || iframe.contentWindow.document;
    iframeDoc.open();
    iframeDoc.write(htmlContent);
    iframeDoc.close();

    await new Promise(r => setTimeout(r, 1500));

    const canvas = await html2canvas(iframeDoc.body, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#ffffff',
    });

    document.body.removeChild(iframe);

    const pdf = new jsPDF('p', 'mm', 'a4');

    const imgData = canvas.toDataURL('image/png');
    const imgWidth = 210;
    const pageHeight = 297;

    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;

    let position = 0;

    // 🔥 FIRST PAGE
    pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
    heightLeft -= pageHeight;

    // 🔥 EXTRA PAGES
    while (heightLeft > 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, 'PNG', 0, position, imgWidth, imgHeight);
      heightLeft -= pageHeight;
    }

    pdf.save(
      `${assignment.title || 'assignment'}_${assignment.selectedFont}_handwritten.pdf`
    );

  } catch (err) {
    console.error(err);
    alert('PDF generation failed');
  } finally {
    setIsDownloading(false);
    setDownloadFormat('');
  }
};

  const fontClass = getFontClass();

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-blue-50">
      <nav className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between h-16">
            <div className="flex items-center">
              <button onClick={() => navigate('/dashboard')} className="flex items-center space-x-2">
                <div className="w-8 h-8 bg-gradient-to-br from-primary-500 to-primary-700 rounded-lg flex items-center justify-center">
                  <svg className="w-5 h-5 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
                  </svg>
                </div>
                <span className="text-xl font-bold text-gray-900">
                  Handwritten<span className="text-primary-600">AI</span>
                </span>
              </button>
            </div>
            <div className="flex items-center">
              <div className={`px-3 py-1 bg-primary-50 rounded-full text-sm ${fontClass} text-primary-700`}>
                Font: {getFontDisplayName(assignment.selectedFont)}
              </div>
            </div>
          </div>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto py-12 px-4 sm:px-6 lg:px-8">
        <div className="bg-white rounded-2xl shadow-xl p-8">
          <div className="text-center mb-8">
            <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <svg className="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
              </svg>
            </div>
            <h1 className="text-3xl font-bold text-gray-900 mb-2">Ready to Download!</h1>
            <p className="text-gray-600">
              Your assignment has been generated with{' '}
              <span className={`font-medium text-primary-600 ${fontClass}`}>
                {getFontDisplayName(assignment.selectedFont)}
              </span>{' '}
              handwriting style
            </p>
            
            {/* Preview of the styling */}
            <div className="mt-6 inline-block px-6 py-3 bg-gray-50 rounded-lg border border-gray-200">
              <div className="flex items-center space-x-3">
                <div className="w-6 h-6 bg-primary-100 rounded flex items-center justify-center">
                  <div className="w-3 h-3 bg-primary-500 rounded-full"></div>
                </div>
                <div>
                  <div className="text-sm text-gray-500">Preview includes:</div>
                  <div className="flex items-center space-x-4 text-sm">
                    <span className="flex items-center">
                      <div className="w-3 h-3 bg-red-500 rounded-sm mr-1"></div>
                      Notebook margin
                    </span>
                    <span className="flex items-center">
                      <div className="w-3 h-px bg-gray-300 mr-1"></div>
                      Lined paper
                    </span>
                    <span className={`${fontClass} text-primary-600`}>
                      {getFontDisplayName(assignment.selectedFont)} font
                    </span>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div className="bg-gray-50 rounded-xl p-6 mb-8">
            <h3 className="font-medium text-gray-900 mb-4">Assignment Details:</h3>
            <div className="space-y-3">
              <div className="flex justify-between">
                <span className="text-gray-600">Title:</span>
                <span className="font-medium">{assignment.title || 'Untitled'}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Handwriting Style:</span>
                <span className={`font-medium text-primary-600 ${fontClass}`}>
                  {getFontDisplayName(assignment.selectedFont)}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Paper Style:</span>
                <span className="font-medium">
                  {assignment.paperType === 'lined' ? 'Lined Paper' : 
                   assignment.paperType === 'grid' ? 'Grid Paper' : 
                   assignment.paperType === 'college' ? 'College Ruled' : 'Plain'}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Questions:</span>
                <span className="font-medium">{assignment.questions.length}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-gray-600">Total Marks:</span>
                <span className="font-medium">
                  {assignment.questions.reduce((sum, q) => sum + (q.marks || 0), 0)}
                </span>
              </div>
            </div>
          </div>

          <div className="space-y-4">
            {/* PDF Download Button */}
            <button
              onClick={handlePDFDownload}
              disabled={isDownloading}
              className="w-full px-6 py-4 bg-gradient-to-r from-primary-600 to-primary-700 text-white rounded-lg hover:from-primary-700 hover:to-primary-800 transition-colors shadow-md hover:shadow-lg flex items-center justify-center disabled:opacity-50"
            >
              {isDownloading && downloadFormat === 'pdf' ? (
                <span className="flex items-center">
                  <svg className="animate-spin -ml-1 mr-2 h-5 w-5 text-white" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Generating PDF with exact preview styling...
                </span>
              ) : (
                <span className="flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                  </svg>
                  Download as PDF (Exact Preview Styling)
                </span>
              )}
            </button>

            {/* Text Download Fallback */}
            <button
              onClick={handleTextDownload}
              disabled={isDownloading}
              className="w-full px-6 py-3 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors flex items-center justify-center disabled:opacity-50"
            >
              {isDownloading && downloadFormat === 'text' ? (
                <span className="flex items-center">
                  <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-gray-600" fill="none" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                  </svg>
                  Preparing Text File...
                </span>
              ) : (
                <span className="flex items-center">
                  <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                  Download as Text File (Simplified)
                </span>
              )}
            </button>

            <div className="bg-blue-50 p-4 rounded-lg">
              <p className="text-sm text-blue-700">
                <strong>PDF Download includes:</strong> Exact same styling as preview - lined paper, notebook margin,{' '}
                <span className="font-medium">{getFontDisplayName(assignment.selectedFont)}</span> handwriting font, 
                and all formatting preserved.
              </p>
            </div>

            <button
              onClick={() => navigate('/preview')}
              className="w-full px-6 py-3 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors flex items-center justify-center"
            >
              <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
              </svg>
              View Preview Again
            </button>

            <button
              onClick={() => navigate('/dashboard')}
              className="w-full px-6 py-3 border border-primary-300 text-primary-600 rounded-lg hover:bg-primary-50 transition-colors flex items-center justify-center"
            >
              <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
              </svg>
              Back to Dashboard
            </button>
          </div>
        </div>
      </main>
    </div>
  );
};

export default DownloadAssignment;